FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=userManagement
ENV MYSQL_DATABASE=userManagement
ENV MYSQL_USER=userManagement
ENV MYSQL_PASSWORD=userManagement

# Exponer el puerto de MySQL
EXPOSE 3306